config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from organizations.backends import invitation_backend, registration_backend


urlpatterns = [
    # our applications
    url(r'^$', TemplateView.as_view(template_name='homepage.html'), name='homepage'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^proposals/', include('proposals.urls', namespace='proposals')),

    # third-party applications
    url(r'^accounts/', include('allauth.urls')),
    url(r'^invitations/', include(invitation_backend().get_urls())),
    url(r'^organizations/', include('organizations.urls')),
    url(r'^register/', include(registration_backend().get_urls())),

    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

proposals/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<organization_slug>[\w-]+)/$',
        views.ProposalList.as_view(),
        name='proposal_list'),
    url(r'^(?P<organization_slug>[\w-]+)/by/(?P<status>[\w-]+)/$',
        views.ProposalList.as_view(),
        name='proposal_list_by_status'),
    url(r'^(?P<organization_slug>[\w-]+)/create/$',
        views.ProposalCreate.as_view(),
        name='proposal_create'),
    url(r'^(?P<organization_slug>[\w-]+)/(?P<pk>[0-9a-f-]+)/$',
        views.ProposalDetail.as_view(),
        name='proposal_detail'),
    url(r'^(?P<organization_slug>[\w-]+)/(?P<pk>[0-9a-f-]+)/delete/$',
        views.ProposalDelete.as_view(),
        name='proposal_delete'),
    url(r'^(?P<organization_slug>[\w-]+)/(?P<pk>[0-9a-f-]+)/draft/$',
        views.ProposalDraft.as_view(),
        name='proposal_draft'),
    url(r'^(?P<organization_slug>[\w-]+)/(?P<pk>[0-9a-f-]+)/raw/$',
        views.ProposalRawDetail.as_view(),
        name='proposal_raw_detail'),
    url(r'^(?P<organization_slug>[\w-]+)/(?P<pk>[0-9a-f-]+)/update/$',
        views.ProposalUpdate.as_view(),
        name='proposal_update'),
    url(r'^(?P<organization_slug>[\w-]+)/(?P<pk>[0-9a-f-]+)/vote/$',
        views.VoteFormView.as_view(),
        name='proposal_vote_form'),
    url(r'^(?P<organization_slug>[\w-]+)/(?P<pk>[0-9a-f-]+)/withdrawn/$',
        views.ProposalWithdrawn.as_view(),
        name='proposal_withdrawn'),
]

proposals/models.py
import uuid

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.functional import cached_property
from markupfield.fields import MarkupField
from simple_history.models import HistoricalRecords

from organizations.models import Organization
from whatnots.models import ContentManageable


DEFAULT_MARKUP_TYPE = getattr(settings, 'DEFAULT_MARKUP_TYPE', 'markdown')


class Proposal(ContentManageable):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    organization = models.ForeignKey(Organization, null=True, blank=True)
    subject = models.TextField()
    body = MarkupField(default_markup_type=DEFAULT_MARKUP_TYPE,
                       null=True, blank=True)
    url = models.TextField(null=True, blank=True)
    closing_date = models.DateField(null=True, blank=True)
    allow_comments = models.BooleanField(default=False)

    STATUS_DRAFT = 'draft'
    STATUS_FINAL = 'final'
    STATUS_WITHDRAWN = 'withdrawn'
    STATUS_ACCEPTED = 'accepted'
    STATUS_REJECTED = 'rejected'
    STATUS_SUPERSEDED = 'superseded'
    STATUS_CHOICES = [
        (STATUS_DRAFT, 'Draft'),
        (STATUS_FINAL, 'Final'),
        (STATUS_WITHDRAWN, 'Withdrawn'),
        (STATUS_ACCEPTED, 'Accepted'),
        (STATUS_REJECTED, 'Rejected'),
        # (STATUS_SUPERSEDED, 'Superseded'),
    ]
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default=STATUS_DRAFT)

    history = HistoricalRecords(excluded_fields=['_body_rendered', 'body_markup_type'])

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse('proposals:proposal_detail', kwargs={
            'organization_slug': self.organization.slug,
            'pk': self.pk,
        })

    def get_accepting_votes(self):
        return self.status in [self.STATUS_DRAFT, self.STATUS_FINAL]

    def get_proposal_vote_form_url(self):
        return reverse('proposals:proposal_vote_form', kwargs={
            'organization_slug': self.organization.slug,
            'pk': self.id,
        })

    @cached_property
    def positive_votes(self):
        votes = Vote.objects.filter(proposal=self, vote=Vote.VOTE_PLUS_ONE).count()
        return votes

    @cached_property
    def neutral_votes(self):
        votes = Vote.objects.filter(proposal=self, vote__in=[Vote.VOTE_PLUS_ZERO, Vote.VOTE_MINUS_ZERO]).count()
        return votes

    @cached_property
    def negative_votes(self):
        votes = Vote.objects.filter(proposal=self, vote=Vote.VOTE_MINUS_ONE).count()
        return votes


class Vote(ContentManageable):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    proposal = models.ForeignKey('proposals.Proposal', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    VOTE_PLUS_ONE = 'plus_one'
    VOTE_PLUS_ZERO = 'plus_zero'
    VOTE_MINUS_ZERO = 'minus_zero'
    VOTE_MINUS_ONE = 'minus_one'
    VOTE_CHOICES = (
        (VOTE_PLUS_ONE, "+1: Yes, I agree"),
        (VOTE_PLUS_ZERO, "+0: I don't feel strongly about it, but I'm okay with this."),
        (VOTE_MINUS_ZERO, "-0: I won't get in the way, but I'd rather we didn't do this."),
        (VOTE_MINUS_ONE, "-1: I object on the following grounds"),
    )
    vote = models.CharField(max_length=16, choices=VOTE_CHOICES, null=True, blank=True)
    reason = models.TextField(null=True, blank=True)

    history = HistoricalRecords()

    class Meta:
        unique_together = (
            ('proposal', 'user'),
        )

    def __str__(self):
        return '{vote} from {proposal} on {proposal}'.format(
            vote=self.get_vote_display(),
            token=self.proposal.subject,
            proposal=self.proposal)

proposals/forms.py
from django import forms
from django.forms.widgets import TextInput, URLInput
from organizations.models import Organization

from . import models
from whatnots.forms import ContentManageableModelForm


class ProposalForm(ContentManageableModelForm):

    def __init__(self, request=None, organization_slug=None, *args, **kwargs):
        self.request = request
        self.organization_slug = organization_slug
        super().__init__(*args, **kwargs)

    class Meta:
        model = models.Proposal
        fields = (
            'subject',
            'body',
            'url',
            'closing_date',
        )
        widgets = {
            'subject': TextInput(),
            'url': URLInput(),
        }

    def save(self, commit=True):
        obj = super().save(commit=False)
        obj.organization = Organization.objects.get(slug=self.organization_slug)

        if commit:
            obj.save()
        return obj


# class VoteForm(ContentManageableModelForm):

#     class Meta:
#         model = models.Vote
#         fields = (
#             'proposal',
#             'user',
#             'vote',
#         )


class VoteForm(forms.Form):
    vote = forms.ChoiceField(widget=forms.RadioSelect, choices=models.Vote.VOTE_CHOICES)
    reason = forms.CharField(widget=forms.Textarea, required=False,
                             help_text='Required for +/-1 votes but optional for +/- 0 votes.')

    def __init__(self, request=None, organization_slug=None, *args, **kwargs):
        self.request = request
        self.organization_slug = organization_slug
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        vote = cleaned_data.get('vote')
        reason = cleaned_data.get('reason')
        if vote in [models.Vote.VOTE_PLUS_ONE, models.Vote.VOTE_MINUS_ONE] and len(reason) == 0:
            msg = 'Please state the reason why you are voting +/- 1'
            self.add_error('reason', msg)

proposals/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView, View
from django.views.generic.edit import FormView

from . import forms
from . import models


class ProposalMixin(object):
    model = models.Proposal
    slug_field = 'pk'

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, self.success_message)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['organization_slug'] = self.kwargs.get('organization_slug')
        return context

    def get_object(self):
        return get_object_or_404(models.Proposal,
                                 organization__slug=self.kwargs.get('organization_slug'),
                                 pk=self.kwargs.get('pk'))


class ProposalCreate(LoginRequiredMixin, ProposalMixin, CreateView):
    form_class = forms.ProposalForm
    success_message = 'Proposal was created'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        kwargs['organization_slug'] = self.kwargs.get('organization_slug')
        return kwargs


class ProposalDelete(LoginRequiredMixin, ProposalMixin, UserPassesTestMixin, DeleteView):
    success_message = 'Proposal was deleted'

    def delete(self, request, *args, **kwargs):
        messages.add_message(self.request, messages.SUCCESS, self.success_message)
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('proposals:proposal_list', kwargs={'organization_slug': self.kwargs.get('organization_slug')})

    def test_func(self):
        return True
        # return self.get_object() == self.request.user


class ProposalDetail(LoginRequiredMixin, ProposalMixin, DetailView):
    template_name = 'proposals/proposal_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.VoteForm()
        return context


class ProposalList(LoginRequiredMixin, ProposalMixin, ListView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status'] = self.kwargs.get('status', models.Proposal.STATUS_DRAFT)
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(organization__slug=self.kwargs.get('organization_slug'))
        status = self.kwargs.get('status', models.Proposal.STATUS_DRAFT)
        if status:
            queryset = queryset.filter(status=status)
        return queryset


class ProposalRawDetail(LoginRequiredMixin, ProposalMixin, DetailView):
    content_type = 'text/plain'
    template_name = 'proposals/proposal_raw_detail.html'


class ProposalUpdate(LoginRequiredMixin, ProposalMixin, UpdateView):
    form_class = forms.ProposalForm
    success_message = 'Proposal was updated'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_action'] = 'update'
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        kwargs['organization_slug'] = self.kwargs.get('organization_slug')
        return kwargs


class ChangeProposalStatus(LoginRequiredMixin, ProposalMixin, View):

    def get(self, request, organization_slug, pk):
        proposal = get_object_or_404(models.Proposal, organization__slug=organization_slug, pk=pk)
        proposal.status = self.new_status
        proposal.save()
        messages.add_message(self.request, messages.SUCCESS, self.success_message)
        return redirect('proposals:proposal_detail', organization_slug=organization_slug, pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = self.get_object()
        return context


class ProposalDraft(ChangeProposalStatus):
    new_status = models.Proposal.STATUS_DRAFT
    success_message = 'Your proposal been re-drafted.'


class ProposalFinal(ChangeProposalStatus):
    new_status = models.Proposal.STATUS_FINAL
    success_message = 'Your proposal been published.'


class ProposalWithdrawn(ChangeProposalStatus):
    new_status = models.Proposal.STATUS_WITHDRAWN
    success_message = 'Your proposal been withdrawn.'


class VoteFormView(LoginRequiredMixin, ProposalMixin, FormView):
    form_class = forms.VoteForm
    success_message = 'Your vote has been recorded.'
    template_name = 'proposals/proposal_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = self.get_object()
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        kwargs['organization_slug'] = self.kwargs.get('organization_slug')
        return kwargs

    def form_valid(self, form):
        print(self.request.user.id)
        print(self.kwargs.get('organization_slug'))
        print(self.kwargs.get('pk'))
        print(form.cleaned_data['vote'])
        vote, created = models.Vote.objects.update_or_create(
            proposal__pk=self.kwargs.get('pk'),
            user=self.request.user.id,
            defaults={
                'vote': form.cleaned_data['vote'],
                'reason': form.cleaned_data.get('reason'),
            }
        )
        print(form.cleaned_data['vote'])
        return super(VoteFormView, self).form_valid(form)

    def get_success_url(self):
        return reverse('proposals:proposal_detail', kwargs={
            'organization_slug': self.kwargs.get('organization_slug'),
            'id': self.kwargs.get('id'),
        })

templates/proposals/base.html
{% extends "base.html" %}

templates/proposals/proposal_confirm_delete.html
{% extends "proposals/base.html" %}

{% block content %}

<h3>Delete Proposal?</h3>

<form action="" method="POST">{% csrf_token %}
<div class="form-group">
  <p>Are you sure you want to delete "{{ object }}"?</p>
</div>
<div class="form-group">
  <button type="submit" class="btn btn-danger">
    Confirm
  </button>
</div>
</form>
{% endblock %}

templates/proposals/proposal_detail.html
{% extends "proposals/base.html" %}

{% load bootstrap4 %}
{% load static %}

{% block content %}

<h2 class="display-4">{{ object.subject }} ({{ object.get_status_display }})</h2>

{% if object.closing_date %}
<h4>{{ object.closing_date }} closing date ({{ object.closing_date|timeuntil }})</h4>
{% endif %}

{% if object.body %}
{{ object.body }}
{% endif %}


{% if object.url %}
{{ object.url }}
{% endif %}

<hr>

<div>
<a class="btn btn-sm btn-primary" href="{% url 'proposals:proposal_update' organization_slug=organization_slug pk=object.pk %}">Update Proposal</a>
<a class="btn btn-sm btn-danger" href="{% url 'proposals:proposal_delete' organization_slug=organization_slug pk=object.pk %}">Delete Proposal</a>
<!--
<a class="btn btn-sm btn-primary" href="{% url 'proposals:proposal_draft' organization_slug=organization_slug pk=object.pk %}">Re-draft</a>
<a class="btn btn-sm btn-danger" href="{% url 'proposals:proposal_withdrawn' organization_slug=organization_slug pk=object.pk %}">Withdraw Proposal</a>
-->
</div>

<hr>

<!-- vote information -->

<p>{{ object.vote_set.count }} vote{{ object.vote_set.count|pluralize }}</p>

<table class="table table-hover table-sm table-striped">
  <thead class="thead-inverse">
    <tr>
      <th>description</th>
      <th>votes</th>
    </tr>
  </thead>
  <tbody>
    <tr scope="row">
      <td>Total Binding +1 votes</td>
      <td>{{ object.positive_votes }}</td>
    </tr>
    <tr scope="row">
      <td>Total Binding  +0/-0 votes</td>
      <td>{{ object.neutral_votes }}</td>
    </tr>
    <tr scope="row">
      <td>Total Binding  -1 votes</td>
      <td>{{ object.negative_votes }}</td>
    </tr>
  </tbody>
</table>

{% if object.get_accepting_votes %}
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">Vote</button>
  {% endbuttons %}
{% endif %}

{% endblock content %}

templates/proposals/proposal_form.html
{% extends "proposals/base.html" %}

{% load bootstrap4 %}

{% block content %}
<h3>Proposal {% if form_action == 'update' %}Update{% else %}Create{% endif %}</h3>

<form action="" method="post" novalidate>
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% if form_action == 'update' %}Update Proposal{% else %}Add Proposal{% endif %}
    </button>
  {% endbuttons %}
</form>
{% endblock %}

templates/proposals/proposal_list.html
{% extends "proposals/base.html" %}

{% block content %}

<h3>Proposal List</h3>

<div>
  <ul class="nav nav-tabs nav-justified">
    <li class="nav-item">
      <a class="nav-link {% if status == 'draft' %}active{% endif %}" href="{% url 'proposals:proposal_list_by_status' organization_slug=organization_slug status='draft' %}">
        Draft
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if status == 'final' %}active{% endif %}" href="{% url 'proposals:proposal_list_by_status' organization_slug=organization_slug status='final' %}">
        Final
    </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if status == 'accepted' %}active{% endif %}" href="{% url 'proposals:proposal_list_by_status' organization_slug=organization_slug status='accepted' %}">
        Accepted
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if status == 'rejected' %}active{% endif %}" href="{% url 'proposals:proposal_list_by_status' organization_slug=organization_slug status='rejected' %}">
        Rejected
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if status == 'withdrawn' %}active{% endif %}" href="{% url 'proposals:proposal_list_by_status' organization_slug=organization_slug status='withdrawn' %}">
        Withdrawn
      </a>
    </li>
    <!--
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
      <div class="dropdown-menu">
        <a class="dropdown-item {% if status == 'rejected' %}active{% endif %}" href="{% url 'proposals:proposal_list_by_status' organization_slug=organization_slug status='rejected' %}">
          Rejected
        </a>
        <a class="dropdown-item {% if status == 'withdrawn' %}active{% endif %}" href="{% url 'proposals:proposal_list_by_status' organization_slug=organization_slug status='withdrawn' %}">
          Withdrawn
        </a>
      </div>
    -->
    </li>
  </ul>
</div>

<div class="list-group">
{% for object in object_list %}
  <a href="{{ object.get_absolute_url }}" class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">{{ object.subject }}</h5>
      {% if object.closing_date %}
      <small>{{ object.closing_date|timeuntil }}</small>
      {% endif %}
    </div>
    {% comment %}
    <small>Donec id elit non mi porta.</small>
    {% endcomment %}
  </a>
{% endfor %}
</div>

<div>
<a class="btn btn-primary" href="{% url 'proposals:proposal_create' organization_slug=organization_slug %}">Create a Proposal</a>
</div>

{% endblock content %}

templates/proposals/proposal_raw_detail.html
{% block content %}## {{ object.subject }}

{{ object.body.raw }}{% endblock content %}